ALTER TYPE "GenerationMode" ADD VALUE IF NOT EXISTS 'TEXT_TO_VIDEO';
ALTER TYPE "GenerationMode" ADD VALUE IF NOT EXISTS 'IMAGE_TO_VIDEO';

ALTER TABLE "Provider" ADD COLUMN "pollTimeoutSeconds" INTEGER NOT NULL DEFAULT 900;

ALTER TABLE "Model" ADD COLUMN "allowedDurations" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "UserGroup" ADD COLUMN "videoQuotaWindow" TEXT;
ALTER TABLE "UserGroup" ADD COLUMN "quotaVideoSeconds" INTEGER;

ALTER TABLE "QuotaEvent" ALTER COLUMN "imageCount" SET DEFAULT 0;
ALTER TABLE "QuotaEvent" ADD COLUMN "videoSeconds" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Asset" ADD COLUMN "durationMs" INTEGER;
